//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recordLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public album()
        {
            this.songs = new HashSet<song>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public System.DateTime dateReleased { get; set; }
        public int ArtistId { get; set; }
        public Nullable<decimal> price { get; set; }
        public string picUrl { get; set; }
        public Nullable<int> CartId { get; set; }
    
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<song> songs { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
