//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recordLabel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<tourDates> tourDates { get; set; }
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<song> songs { get; set; }
        public virtual DbSet<Member> Members1 { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
    }
}
