//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recordLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public string size { get; set; }
        public int ArtistId { get; set; }
        public string picUrl { get; set; }
        public bool onSale { get; set; }
        public Nullable<int> CartId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
