//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recordLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourDates
    {
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public string venue { get; set; }
        public decimal price { get; set; }
        public int ArtistId { get; set; }
        public string location { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
